//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player/PlayerInputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputMap"",
    ""maps"": [
        {
            ""name"": ""OnFoot"",
            ""id"": ""3ef8062e-fa1b-4f80-a746-c40dcc1eda55"",
            ""actions"": [
                {
                    ""name"": ""Movimiento"",
                    ""type"": ""Value"",
                    ""id"": ""a33d215f-550c-4b56-ac12-b02f2501b6f4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FijarObjetivo"",
                    ""type"": ""Button"",
                    ""id"": ""e3bdd667-e61d-4f49-b0fc-c0102486421d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AtaqueLigero"",
                    ""type"": ""Button"",
                    ""id"": ""7f4cf49d-5526-4759-ac25-a82c4def9b2c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AtaquePesado"",
                    ""type"": ""Button"",
                    ""id"": ""ce83ddcb-9ad7-4fed-9d7b-a1df30de7ebb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bloqueo"",
                    ""type"": ""Button"",
                    ""id"": ""b2ce4dff-57e3-42d4-a01e-372b9247ae98"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0cac0c00-3083-4248-a0af-857e2a762299"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f4c0b147-fb4d-4c13-a582-a79ddfa051e5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f83aebca-8957-42d5-936a-fe21b5124ccd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b32eb46d-4727-4a05-b525-159c54656f10"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2bfbbd16-7416-4acf-b752-374a7e98ea01"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e4e7d948-2610-4fdc-bc41-feae90d21170"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movimiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""aa832ef0-3729-4d0c-94fe-cb9b76cb8983"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FijarObjetivo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c0c6329-b9fc-4276-9ac6-762d9adce7ce"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AtaqueLigero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c90494fe-9a26-46bc-9c55-951bc8138d89"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AtaqueLigero"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3699547-e14d-46f2-bbaf-b28220098b19"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AtaquePesado"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf3a524d-4ce2-4048-bdc8-d1ea1665d8c0"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bloqueo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // OnFoot
        m_OnFoot = asset.FindActionMap("OnFoot", throwIfNotFound: true);
        m_OnFoot_Movimiento = m_OnFoot.FindAction("Movimiento", throwIfNotFound: true);
        m_OnFoot_FijarObjetivo = m_OnFoot.FindAction("FijarObjetivo", throwIfNotFound: true);
        m_OnFoot_AtaqueLigero = m_OnFoot.FindAction("AtaqueLigero", throwIfNotFound: true);
        m_OnFoot_AtaquePesado = m_OnFoot.FindAction("AtaquePesado", throwIfNotFound: true);
        m_OnFoot_Bloqueo = m_OnFoot.FindAction("Bloqueo", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // OnFoot
    private readonly InputActionMap m_OnFoot;
    private List<IOnFootActions> m_OnFootActionsCallbackInterfaces = new List<IOnFootActions>();
    private readonly InputAction m_OnFoot_Movimiento;
    private readonly InputAction m_OnFoot_FijarObjetivo;
    private readonly InputAction m_OnFoot_AtaqueLigero;
    private readonly InputAction m_OnFoot_AtaquePesado;
    private readonly InputAction m_OnFoot_Bloqueo;
    public struct OnFootActions
    {
        private @PlayerInputMap m_Wrapper;
        public OnFootActions(@PlayerInputMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movimiento => m_Wrapper.m_OnFoot_Movimiento;
        public InputAction @FijarObjetivo => m_Wrapper.m_OnFoot_FijarObjetivo;
        public InputAction @AtaqueLigero => m_Wrapper.m_OnFoot_AtaqueLigero;
        public InputAction @AtaquePesado => m_Wrapper.m_OnFoot_AtaquePesado;
        public InputAction @Bloqueo => m_Wrapper.m_OnFoot_Bloqueo;
        public InputActionMap Get() { return m_Wrapper.m_OnFoot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OnFootActions set) { return set.Get(); }
        public void AddCallbacks(IOnFootActions instance)
        {
            if (instance == null || m_Wrapper.m_OnFootActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OnFootActionsCallbackInterfaces.Add(instance);
            @Movimiento.started += instance.OnMovimiento;
            @Movimiento.performed += instance.OnMovimiento;
            @Movimiento.canceled += instance.OnMovimiento;
            @FijarObjetivo.started += instance.OnFijarObjetivo;
            @FijarObjetivo.performed += instance.OnFijarObjetivo;
            @FijarObjetivo.canceled += instance.OnFijarObjetivo;
            @AtaqueLigero.started += instance.OnAtaqueLigero;
            @AtaqueLigero.performed += instance.OnAtaqueLigero;
            @AtaqueLigero.canceled += instance.OnAtaqueLigero;
            @AtaquePesado.started += instance.OnAtaquePesado;
            @AtaquePesado.performed += instance.OnAtaquePesado;
            @AtaquePesado.canceled += instance.OnAtaquePesado;
            @Bloqueo.started += instance.OnBloqueo;
            @Bloqueo.performed += instance.OnBloqueo;
            @Bloqueo.canceled += instance.OnBloqueo;
        }

        private void UnregisterCallbacks(IOnFootActions instance)
        {
            @Movimiento.started -= instance.OnMovimiento;
            @Movimiento.performed -= instance.OnMovimiento;
            @Movimiento.canceled -= instance.OnMovimiento;
            @FijarObjetivo.started -= instance.OnFijarObjetivo;
            @FijarObjetivo.performed -= instance.OnFijarObjetivo;
            @FijarObjetivo.canceled -= instance.OnFijarObjetivo;
            @AtaqueLigero.started -= instance.OnAtaqueLigero;
            @AtaqueLigero.performed -= instance.OnAtaqueLigero;
            @AtaqueLigero.canceled -= instance.OnAtaqueLigero;
            @AtaquePesado.started -= instance.OnAtaquePesado;
            @AtaquePesado.performed -= instance.OnAtaquePesado;
            @AtaquePesado.canceled -= instance.OnAtaquePesado;
            @Bloqueo.started -= instance.OnBloqueo;
            @Bloqueo.performed -= instance.OnBloqueo;
            @Bloqueo.canceled -= instance.OnBloqueo;
        }

        public void RemoveCallbacks(IOnFootActions instance)
        {
            if (m_Wrapper.m_OnFootActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOnFootActions instance)
        {
            foreach (var item in m_Wrapper.m_OnFootActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OnFootActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OnFootActions @OnFoot => new OnFootActions(this);
    public interface IOnFootActions
    {
        void OnMovimiento(InputAction.CallbackContext context);
        void OnFijarObjetivo(InputAction.CallbackContext context);
        void OnAtaqueLigero(InputAction.CallbackContext context);
        void OnAtaquePesado(InputAction.CallbackContext context);
        void OnBloqueo(InputAction.CallbackContext context);
    }
}
